platform :ios, '7.1'
pod 'MagicalRecord/Shorthand', '2.2'
pod 'HPGrowingTextView', '1.1'
pod 'HPReorderTableView', '0.2'
pod 'TPKeyboardAvoiding', :git => 'https://github.com/michaeltyson/TPKeyboardAvoiding.git'
